version: '3.8'

services:
  firebase-emulators:
    image: node:18-alpine
    build:
      context: .
      dockerfile: docker/emulators.Dockerfile
    container_name: kua-emulators
    restart: unless-stopped
    ports:
      - "4000:4000"   # Emulator UI
      - "8080:8080"   # Firestore
      - "9099:9099"   # Authentication
      - "9199:9199"   # Storage
      - "5001:5001"   # Cloud Functions
    volumes:
      - emulator-data:/root/.cache/firebase/emulators
      - ./backend:/workspace
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIREBASE_AUTH_EMULATOR_HOST=auth:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=storage:9199
      - FUNCTIONS_EMULATOR_HOST=functions:5001
      - GCP_PROJECT=kua-dev
    networks:
      - kua-network

  flutter-web:
    image: nginx:alpine
    container_name: kua-webapp
    restart: unless-stopped
    ports:
      - "8081:80"   # Flutter web di port 8081, karena 8080 sudah dipakai emulator
    volumes:
      - ./frontend/build/web:/usr/share/nginx/html
    networks:
      - kua-network

volumes:
  emulator-data:
    driver: local

networks:
  kua-network:
    driver: bridge