version: '3.8'

services:
  firebase-emulators:
    image: kua-emulators:latest
    build:
      context: .
      dockerfile: docker/emulators.Dockerfile
    container_name: kua-emulators
    restart: unless-stopped
    ports:
      - "4100:4000"   # Emulator UI - PORT BARU
      - "8282:8080"   # Firestore - PORT BARU  
      - "9190:9099"   # Authentication - PORT BARU
      - "9292:9199"   # Storage - PORT BARU
      - "5100:5001"   # Cloud Functions - PORT BARU
    volumes:
      - emulator-data:/root/.cache/firebase/emulators

    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - FIREBASE_AUTH_EMULATOR_HOST=auth:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=storage:9199
      - FUNCTIONS_EMULATOR_HOST=functions:5001
      - GCP_PROJECT=kua-dev
    networks:
      - kua-network

volumes:
  emulator-data:
    driver: local

networks:
  kua-network:
    driver: bridge
    name: kua-network-v2   # Nama jaringan unik